POSITIVE = {
    "avanço","avanços","avançado","conquista","conquistas","benefício","benefícios",
    "inovação","inovações","crescimento","cresceu","crescente","desenvolvimento",
    "desenvolvido","desenvolvidos","progressos","melhoria","melhorias","aprimoramento",
    "evolução","evoluções","transformação","transformador","expansão","expandido",
    "fortalecimento","fortalecido","eficiência","eficiente","sustentabilidade","sustentável",
    "inclusão","inclusivo","acessível","acessibilidade","gratuito","gratuitos","gratuita",
    "autorizado","autorização","aprovado","aprovação","apoio","apoiado","cooperação",
    "cooperativo","parceria","parcerias","aliança","acordo","colaboração","colaborativo",
    "integração","integrado","investimento","investimentos","financiado","financiamento",
    "recurso","recursos","aporte","crédito","sucesso","bem-sucedido","vitória","vitórias",
    "ganho","ganhos","resultado positivo","destaque","premiado","premiados","premiação",
    "reconhecimento","celebração","celebrado","inspiração","inspirador","motivação",
    "esperança","esperançoso","otimismo","otimista","resolução","resolvido","solução",
    "soluções","transparência","transparente","segurança","seguro","estabilidade",
    "confiança","confiável","credibilidade","legitimidade","liderança","líder","líderes",
    "impacto positivo","educação","educacional","capacitação","capacitado","treinamento",
    "formação","formados","qualificação","aprendizagem","aprendizado","conhecimento",
    "sabedoria","ciência","científico","tecnologia","tecnológico","modernização",
    "modernizado","digital","transformação digital","empreendedor","empreendedorismo",
    "fortalecimento regional","apoio comunitário","cidadania","democracia","democrático",
    "governança","governabilidade","serviço eficiente","programa","programas","projeto",
    "projetos","lançamento","lançado","inauguração","inaugurado","evento","eventos",
    "campanha","iniciativa","pioneiro","pioneira","popularização","popularizado",
    "empoderamento","empoderado","justiça","equidade","igualdade","diversidade",
    "prosperidade","próspero","riqueza","valorização","valorizado","patrimônio preservado",
    "preservação","conservação","proteção ambiental","clima positivo","redução da pobreza",
    "erradicação da pobreza","fome zero","bem-estar","qualidade de vida","saúde",
    "saudável","cura","prevenção","avanço político","estabilidade política",
    "crescimento econômico","progresso regional","infraestrutura moderna","conectividade",
    "cidades inteligentes","preservado","meio ambiente","sustentabilidade ambiental",
    "democratização","solidariedade","humanização","voluntariado","bem comum","crescimento sustentável","recuperação","superação","vitória histórica",
    "modernização digital","liderança mundial","cooperação internacional",
    "redução da pobreza","fome zero","energia limpa","renovável","reciclagem",
    "conservação ambiental","premiação internacional","recorde","campeão",
    "campeã","herói","heróico","solidário","humanitário","ajuda humanitária",
    "apoio emergencial","reconstrução","reerguimento","vitórias sociais",
    "avanço científico","cura","tratamento eficaz","vacina","descoberta",
    "descobertas científicas","expansão tecnológica","crescimento global",
    "segurança reforçada","infraestrutura concluída","construção finalizada",
    "pontes inauguradas","escolas entregues","hospital inaugurado",
}


NEGATIVE = {
    "crise","crises","problema","problemas","dificuldade","dificuldades","falha","falhas",
    "erro","erros","atraso","atrasos","demora","corte","cortes","redução","reduções",
    "queda","quedas","perdas","prejuízo","prejuízos","déficit","deficits","deficitário",
    "endividado","endividamento","dívida","dívidas","fracasso","fracassado","fracassados",
    "fracassada","rejeitado","rejeitada","rejeição","recusa","recusado","recusada",
    "contestação","instável","instabilidade","criticado","crítica","críticas","acusado",
    "acusação","acusações","denúncia","denúncias","polêmica","polêmicas","escândalo",
    "escândalos","fraude","fraudes","ilegal","ilegalidade","irregular","irregularidades",
    "corrupção","corrupto","investigado","investigação","suspeita","suspeito","processo",
    "processado","condenado","crime","crimes","criminoso","assassinato","homicídio",
    "violência","violento","ataque","ataques","agressão","ameaça","ameaças","terrorismo",
    "trágico","tragédia","colapso","falência","ruína","catástrofe","desastre","desesperado",
    "pânico","caos","caótico","explosão","incêndio","acidente","vazamento","contaminação",
    "doença","doenças","epidemia","pandemia","isolamento","bloqueio","embargo","suspenso",
    "interdição","inconstitucional","ilegítimo","desvalorização","inflação","desemprego",
    "pobreza","miserável","miséria","fome","carência","abandono","negligência","insegurança",
    "medo","risco","perigoso","perda","ruído","ciberataque","hacker","malware","vírus",
    "contágio","retrocesso","atraso estrutural","regressão","repressão","censura","perseguição",
    "discriminação","racismo","xenofobia","homofobia","misoginia","machismo","intolerância",
    "violação","abuso","exploração","escravidão","tráfico","contrabando","assédio",
    "bullying","crime cibernético","golpe","golpista","hackeado","sequestro","terrorismo digital",
    "guerra","conflito","tensão","hostilidade","destruição","devastação","desmatamento",
    "aquecimento global","crise climática","escassez","corrupção política","fraude eleitoral",
    "sanção","retirada","boicote","acusação formal","contestação judicial","impedimento",
    "bloqueado","suspensão","colapso econômico","piora","preocupação","desafio",
    "assalto","assaltos","assaltante","assaltantes","assaltada","assaltado","assaltaram","assaltava","assaltando",
    "enchente","enchentes","alagamento","alagamentos","inundação","inundações",
    "seca","secas","estiagem","terremoto","terremotos","tsunami","furacão",
    "furacões","tufão","tufões","ciclone","ciclones","deslizamento","deslizamentos",
    "tragédia ambiental","colapso estrutural","apagão","apagões","pane elétrica",
    "pane geral","explosão nuclear","acidente aéreo","queda de avião",
    "naufrágio","afundamento","colisão","choque","engavetamento","massacre",
    "genocídio","execução","atentado","tiroteio","assassinato coletivo",
    "rebelião","revolta","guerra civil","bombardeio","ataque terrorista",
    "sequestro relâmpago","roubo","roubos","assalto","assaltos","latrocínio",
    "corrupção endêmica","crime organizado","tráfico de drogas","tráfico humano",
    "extorsão","sequestro internacional","pirataria","piratas","pirataria digital",
    "crime ambiental","desmatamento ilegal","incêndio florestal","queimada",
    "queimadas ilegais","contaminação tóxica","radiação","poluição extrema",
    "colapso econômico","quebra da bolsa","recessão","hiperinflação","desemprego recorde",
    "carestia","escassez de alimentos","escassez hídrica","racionamento","fome",
    "miséria extrema","marginalização","violência urbana","violência doméstica",
}
